spring:
  application:
    name: jt808
  data:
    mongodb:
      uri: mongodb+srv://taxieco_dev:cDWggNaNhAi0jB6e@taxieco.nfp6huo.mongodb.net/zendo
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

mybatis-plus:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations:
    - classpath:/mapper/*.xml

server:
  port: 8100

oci:
  auth-type: INSTANCE_PRINCIPAL # Options: CONFIG_FILE, INSTANCE_PRINCIPAL
  config:
    file-path: ~/.oci/config
    profile: DEFAULT
  bucket: zendo-dev
  namespace: ax0s9dy3myes
  region: ap-singapore-1

jt-server:
  jt808:
    tcp-port: 7100
    udp-port: 7100
    idle-timeout: 180
    message-package: org.yzh.protocol
    t0801:
      path: ./jt_data/media_file
    t9208:
      host: 152.69.210.81
      port: 10780
      enabled: true
      path: ./jt_data/alarm_file
    t9206:
      host: 152.69.210.81
      port: 21
      username: test
      password: test